service: tesco-dojo-receipt

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1

functions:
  receipt:
    handler: handler.receipt
    events:
      - sns:
          arn: arn:aws:sns:eu-west-1:520564598135:tesco-dojo-orders

